const TRAER_ZONAS = 'TRAER_ZONAS';
const SELECCIONAR = 'SELECCIONAR_ZONA';
const LOADING = 'ZONA_LOADING';
const ERROR = 'ZONA_ERROR';
const LIMPIAR_ACTIVO = 'ZONA_LIMPIAR_ACTIVO';

export {TRAER_ZONAS,SELECCIONAR,LOADING,ERROR,LIMPIAR_ACTIVO}